config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  get '/main', to: 'main#index'
  get '/catalogue', to: 'main#catalogue'
  get '/configurator', to: 'configurator#index'

  resources :components
  resources :catalogue
  resources :configurator
  resources :games


  resource :session, only: %i[new create destroy]
  resources :users
  resources :line_items, only: [:create, :update, :destroy]

  resources :rams
  resources :ssds
  resources :hdds
  resources :motherboards
  resources :cpus
  resources :gpus
  resources :power_supplies
  resources :rigs
  resources :coolers
  

  get 'session', to: 'sessions#new'
  get 'step1', to: 'configurator#step1'
  post 'step1_submit', to: 'configurator#step1_submit'
  get 'step2', to: 'configurator#step2'
  post 'step2_submit', to: 'configurator#step2_submit'
  get 'step3', to: 'configurator#step3'
  post 'step3_submit', to: 'configurator#step3_submit'
  get 'results', to: 'configurator#results'
  post 'results', to: 'configurator#results'
  patch '/users/:id', to: 'users#update', as: :update_user

  get '/step2', to: 'configurator#step2'
  get '/step3', to: 'configurator#step3'
  get '/main', to: 'components#show'
  get '/cart', to: 'cart#index'
  get '/news', to: 'main#news'
  get '/support', to: 'main#support'
  get '/about', to: 'main#about'
  get '/login', to: 'main#login'
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :line_items, dependent: :destroy

    def add_component(component)
        line_item = line_items.find_by(component_id: component.id)
        if line_item
          line_item.quantity += 1
        else
          line_item = line_items.build(component_id: component.id)
        end
        line_item.save
    end
end

app/models/component.rb
class Component < ApplicationRecord
    has_one_attached :image
    has_many :line_items
end

app/models/cooler.rb
class Cooler < ApplicationRecord
    has_one_attached :image
end

app/models/cpu.rb
class Cpu < ApplicationRecord
    has_one_attached :image
end

app/models/game.rb
class Game < ApplicationRecord
    has_one_attached :image
end

app/models/gpu.rb
class Gpu < ApplicationRecord
    has_one_attached :image
end

app/models/hdd.rb
class Hdd < ApplicationRecord
    has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :component
  belongs_to :cart
end

app/models/motherboard.rb
class Motherboard < ApplicationRecord
    has_one_attached :image
end

app/models/power_supply.rb
class PowerSupply < ApplicationRecord
    has_one_attached :image
end

app/models/ram.rb
class Ram < ApplicationRecord
    has_one_attached :image
end

app/models/rig.rb
class Rig < ApplicationRecord
    has_one_attached :image
end

app/models/ssd.rb
class Ssd < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  before_save :downcase_nickname
  has_one :cart

  validates :email, presence: true, uniqueness: true

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/power_supplies_controller.rb
class PowerSuppliesController < ApplicationController
  def index
    @power_supplies = PowerSupply.all
  end

  def show
    @power_supply = PowerSupply.find(params[:id])
  end

  def new
    @power_supply = PowerSupply.new
  end

  def create
    @power_supply = PowerSupply.new(power_supply_params)
    if @power_supply.save
      redirect_to @power_supply
    else
      render 'new'
    end
  end

  def edit
    @power_supply = PowerSupply.find(params[:id])
  end

  def update
    @power_supply = PowerSupply.find(params[:id])
    if @power_supply.update(power_supply_params)
      redirect_to @power_supply
    else
      render 'edit'
    end
  end

  def destroy
    @power_supply = PowerSupply.find(params[:id])
    @power_supply.destroy
    redirect_to power_supplies_path
  end

  private

  def power_supply_params
    params.require(:power_supply).permit(:brand, :model, :wattage, :price, :efficiency, :form_factor, :rating, :image)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/helpers/gpus_helper.rb
module GpusHelper
end

app/helpers/hdds_helper.rb
module HddsHelper
end

app/helpers/power_supplies_helper.rb
module PowerSuppliesHelper
end

app/helpers/rams_helper.rb
module RamsHelper
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/helpers/ssds_helper.rb
module SsdsHelper
end

app/views/power_supplies/edit.html.erb
<h2>Edit POWER_SUPPLY</h2>
<%= form_with(model: @power_supply, url: power_supply_path(@power_supply), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %><br>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: 'form-control' %><br>
    <%= form.label :wattage %>
    <%= form.number_field :wattage, class: 'form-control' %><br>
    <%= form.label :efficiency %>
    <%= form.number_field :efficiency, class: 'form-control' %><br>
    <%= form.label :form_factor %>
    <%= form.text_field :form_factor, class: 'form-control' %><br>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: 'form-control' %><br>
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.01, class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
      <% if @power_supply.image.attached? %>
      <div>
        <%= image_tag(@power_supply.image) %>
      </div>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.submit 'Update POWER SUPPLY' %>
  </div>
<% end %>

app/views/power_supplies/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main style="background: linear-gradient(to bottom, #000000, #1a0d0d, #1a0d0d, #000000)">
    <div class="container">
      <h2 class="components__title-all">POWER SUPPLY</h2>
      <div class="component__logo all__components">
        <% @power_supplies.each do |power_supply| %>
          <div class="component__item">
            <div class="component__title-main"><%= link_to power_supply.model, "/power_supplies/#{power_supply.id}" %></div>
            <%= image_tag(power_supply.image) %>
            <div class="component__description"><br>
              <%= power_supply.brand %>
              <span class="description__label"></span>
              <% rating = power_supply.rating.round(1) %>
              <span class="stars">
                <% for i in 1..5 do %>
                  <% if rating >= i %>
                    <%= image_tag('bg/star.png') %>
                  <% elsif rating >= i - 0.5 && rating < i %>
                    <%= image_tag('bg/half-star.png') %>
                  <% else %>
                    <%= image_tag('bg/empty-star.png') %>
                  <% end %>
                <% end %>
              </span>
              <span class="price__label">Price: <%= power_supply.price %> $USD</span>
              <span class="more__info"><%= link_to 'See more', "/power_supplies/#{power_supply.id}" %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>

app/views/power_supplies/new.html.erb
<h1>Create new POWER_SUPPLY</h1>

<%= form_with(model: @power_supply, local: true) do |form| %>
  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %><br>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: 'form-control' %><br>
    <%= form.label :wattage %>
    <%= form.number_field :wattage, class: 'form-control' %><br>
    <%= form.label :efficiency %>
    <%= form.number_field :efficiency, class: 'form-control' %><br>
    <%= form.label :form_factor %>
    <%= form.text_field :form_factor, class: 'form-control' %><br>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: 'form-control' %><br>
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.01, class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', power_supplies_path %>

app/views/power_supplies/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main style="background: linear-gradient(to bottom, #000000, #1a0d0d, #1a0d0d, #000000)">
    <div class="container">
      <h1><%= @power_supply.model %></h1>
      <% if @power_supply.image.attached? %>
        <div class="component-pic">
          <%= image_tag(@power_supply.image) %>
        </div>
      <% end %>
      <div class="main__component-info">
        <p>Бренд: <%= @power_supply.brand %></p>
        <p>Цена: <%= number_to_currency(@power_supply.price) %></p>
      </div>
      <div class="action-buttons__all">
        <%= link_to "Edit component", edit_power_supply_path(@power_supply) %>
        <%= button_to 'Delete component', power_supply_path(@power_supply), method: :delete %><br>
        <%= link_to "All power supplies", power_supplies_path %>
      </div>
    </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>