config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  get '/main', to: 'main#index'
  get '/catalogue', to: 'main#catalogue'
  get '/configurator', to: 'configurator#index'

  resources :components
  resources :catalogue
  resources :configurator
  resources :games


  resource :session, only: %i[new create destroy]
  resources :users
  resources :line_items, only: [:create, :update, :destroy]

  resources :rams
  resources :ssds
  resources :hdds
  resources :motherboards
  resources :cpus
  resources :gpus
  resources :power_supplies
  resources :rigs
  resources :coolers
  

  get 'session', to: 'sessions#new'
  get 'step1', to: 'configurator#step1'
  post 'step1_submit', to: 'configurator#step1_submit'
  get 'step2', to: 'configurator#step2'
  post 'step2_submit', to: 'configurator#step2_submit'
  get 'step3', to: 'configurator#step3'
  post 'step3_submit', to: 'configurator#step3_submit'
  get 'results', to: 'configurator#results'
  post 'results', to: 'configurator#results'
  patch '/users/:id', to: 'users#update', as: :update_user

  get '/step2', to: 'configurator#step2'
  get '/step3', to: 'configurator#step3'
  get '/main', to: 'components#show'
  get '/cart', to: 'cart#index'
  get '/news', to: 'main#news'
  get '/support', to: 'main#support'
  get '/about', to: 'main#about'
  get '/login', to: 'main#login'
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :line_items, dependent: :destroy

    def add_component(component)
        line_item = line_items.find_by(component_id: component.id)
        if line_item
          line_item.quantity += 1
        else
          line_item = line_items.build(component_id: component.id)
        end
        line_item.save
    end
end

app/models/component.rb
class Component < ApplicationRecord
    has_one_attached :image
    has_many :line_items
end

app/models/cooler.rb
class Cooler < ApplicationRecord
    has_one_attached :image
end

app/models/cpu.rb
class Cpu < ApplicationRecord
    has_one_attached :image
end

app/models/game.rb
class Game < ApplicationRecord
    has_one_attached :image
end

app/models/gpu.rb
class Gpu < ApplicationRecord
    has_one_attached :image
end

app/models/hdd.rb
class Hdd < ApplicationRecord
    has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :component
  belongs_to :cart
end

app/models/motherboard.rb
class Motherboard < ApplicationRecord
    has_one_attached :image
end

app/models/power_supply.rb
class PowerSupply < ApplicationRecord
    has_one_attached :image
end

app/models/ram.rb
class Ram < ApplicationRecord
    has_one_attached :image
end

app/models/rig.rb
class Rig < ApplicationRecord
    has_one_attached :image
end

app/models/ssd.rb
class Ssd < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  before_save :downcase_nickname
  has_one :cart

  validates :email, presence: true, uniqueness: true

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/ssds_controller.rb
class SsdsController < ApplicationController
  def index
    @ssds = Ssd.all
  end

  def show
    @ssd = Ssd.find(params[:id])
  end

  def new
    @ssd = Ssd.new
  end

  def create
    @ssd = Ssd.new(ssd_params)
    if @ssd.save
      redirect_to @ssd
    else
      render :new
    end
  end

  def edit
    @ssd = Ssd.find(params[:id])
  end

  def update
    @ssd = Ssd.find(params[:id])
    if @ssd.update(ssd_params)
      redirect_to @ssd
    else
      render :edit
    end
  end

  def destroy
    @ssd = Ssd.find(params[:id])
    @ssd.destroy
    redirect_to ssds_path
  end

  private

  def ssd_params
    params.require(:ssd).permit(:capacity, :type, :brand, :price, :compatibility, :model, :interface, :form_factor, :read_speed, :write_speed, :compatible_interface, :rating, :image, :operating_time, :write_resource)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gpus_helper.rb
module GpusHelper
end

app/helpers/hdds_helper.rb
module HddsHelper
end

app/helpers/rams_helper.rb
module RamsHelper
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/helpers/ssds_helper.rb
module SsdsHelper
end

app/views/ssds/edit.html.erb
<h2>Edit SSD</h2>
<%= form_with(model: @ssd, url: ssd_path(@ssd), method: :patch) do |form| %>
  <div class="field">
    <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %><br>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: 'form-control' %><br>
    <%= form.label :capacity %>
    <%= form.number_field :capacity, class: 'form-control' %><br>
    <%= form.label :interface %>
    <%= form.text_field :interface, class: 'form-control' %><br>
    <%= form.label :form_factor %>
    <%= form.text_field :form_factor, class: 'form-control' %><br>
    <%= form.label :read_speed %>
    <%= form.text_field :read_speed, class: 'form-control' %><br>
    <%= form.label :write_speed %>
    <%= form.text_field :write_speed, class: 'form-control' %><br>
    <%= form.label :compatible_interface %>
    <%= form.text_field :compatible_interface, class: 'form-control' %><br>
    <%= form.label :write_resource %>
    <%= form.number_field :write_resource, class: 'form-control' %><br>
    <%= form.label :operating_time %>
    <%= form.number_field :operating_time, class: 'form-control' %><br>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: 'form-control' %><br>
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.01, class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
      <% if @ssd.image.attached? %>
      <div>
        <%= image_tag(@ssd.image) %>
      </div>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.submit 'Update SSD' %>
  </div>
<% end %>

app/views/ssds/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main style="background: linear-gradient(to bottom, #000000, #1a0d0d, #1a0d0d, #000000)">
    <div class="container">
      <h2 class="components__title-all">SSD</h2>
      <div class="component__logo all__components">
        <% @ssds.each do |ssd| %>
          <div class="component__item">
            <div class="component__title-main"><%= link_to ssd.model, "/ssds/#{ssd.id}" %></div>
            <%= image_tag(ssd.image) %>
            <div class="component__description"><br>
              <%= ssd.brand %>
              <span class="description__label"></span>
              <% rating = ssd.rating.round(1) %>
              <span class="stars">
                <% for i in 1..5 do %>
                  <% if rating >= i %>
                    <%= image_tag('bg/star.png') %>
                  <% elsif rating >= i - 0.5 && rating < i %>
                    <%= image_tag('bg/half-star.png') %>
                  <% else %>
                    <%= image_tag('bg/empty-star.png') %>
                  <% end %>
                <% end %>
              </span>
              <span class="price__label">Price: <%= ssd.price %> $USD</span>
              <span class="more__info"><%= link_to 'See more', "/ssds/#{ssd.id}" %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>

app/views/ssds/new.html.erb
<h1>Create new SSD</h1>

<%= form_with(model: @ssd, local: true) do |form| %>
  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %><br>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: 'form-control' %><br>
    <%= form.label :capacity %>
    <%= form.number_field :capacity, class: 'form-control' %><br>
    <%= form.label :interface %>
    <%= form.text_field :interface, class: 'form-control' %><br>
    <%= form.label :form_factor %>
    <%= form.text_field :form_factor, class: 'form-control' %><br>
    <%= form.label :read_speed %>
    <%= form.text_field :read_speed, class: 'form-control' %><br>
    <%= form.label :write_speed %>
    <%= form.text_field :write_speed, class: 'form-control' %><br>
    <%= form.label :compatible_interface %>
    <%= form.text_field :compatible_interface, class: 'form-control' %><br>
    <%= form.label :write_resource %>
    <%= form.number_field :write_resource, class: 'form-control' %><br>
    <%= form.label :operating_time %>
    <%= form.number_field :operating_time, class: 'form-control' %><br>
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: 'form-control' %><br>
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.01, class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', ssds_path %>

app/views/ssds/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main style="background: linear-gradient(to bottom, #000000, #1a0d0d, #1a0d0d, #000000)">
    <div class="container">
      <h1><%= @ssd.model %></h1>
      <% if @ssd.image.attached? %>
        <div>
          <%= image_tag(@ssd.image) %>
        </div>
      <% end %>
      <div class="main__component-info">
        <p>Бренд: <%= @ssd.brand %></p>
        <p>Цена: <%= number_to_currency(@ssd.price) %></p>
      </div>
      <div class="action-buttons__all">
        <%= link_to "Edit component", edit_ssd_path(@ssd) %>
        <%= button_to 'Delete component', ssd_path(@ssd), method: :delete %><br>
        <%= link_to "All ssds", ssds_path %>
      </div>
    </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>