config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  get '/main', to: 'main#index'
  get '/catalogue', to: 'main#catalogue'
  get '/configurator', to: 'configurator#index'

  resources :components
  resources :catalogue
  resources :configurator
  resources :games


  resource :session, only: %i[new create destroy]
  resources :users
  resources :line_items, only: [:create, :update, :destroy]

  resources :rams
  resources :ssds
  resources :hdds
  resources :motherboards
  resources :cpus
  resources :gpus
  resources :power_supplies
  resources :rigs
  resources :coolers
  

  get 'session', to: 'sessions#new'
  get 'step1', to: 'configurator#step1'
  post 'step1_submit', to: 'configurator#step1_submit'
  get 'step2', to: 'configurator#step2'
  post 'step2_submit', to: 'configurator#step2_submit'
  get 'step3', to: 'configurator#step3'
  post 'step3_submit', to: 'configurator#step3_submit'
  get 'results', to: 'configurator#results'
  post 'results', to: 'configurator#results'
  patch '/users/:id', to: 'users#update', as: :update_user

  get '/step2', to: 'configurator#step2'
  get '/step3', to: 'configurator#step3'
  get '/main', to: 'components#show'
  get '/cart', to: 'cart#index'
  get '/news', to: 'main#news'
  get '/support', to: 'main#support'
  get '/about', to: 'main#about'
  get '/login', to: 'main#login'
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :line_items, dependent: :destroy

    def add_component(component)
        line_item = line_items.find_by(component_id: component.id)
        if line_item
          line_item.quantity += 1
        else
          line_item = line_items.build(component_id: component.id)
        end
        line_item.save
    end
end

app/models/component.rb
class Component < ApplicationRecord
    has_one_attached :image
    has_many :line_items
end

app/models/cooler.rb
class Cooler < ApplicationRecord
    has_one_attached :image
end

app/models/cpu.rb
class Cpu < ApplicationRecord
    has_one_attached :image
end

app/models/game.rb
class Game < ApplicationRecord
    has_one_attached :image
end

app/models/gpu.rb
class Gpu < ApplicationRecord
    has_one_attached :image
end

app/models/hdd.rb
class Hdd < ApplicationRecord
    has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :component
  belongs_to :cart
end

app/models/motherboard.rb
class Motherboard < ApplicationRecord
    has_one_attached :image
end

app/models/power_supply.rb
class PowerSupply < ApplicationRecord
    has_one_attached :image
end

app/models/ram.rb
class Ram < ApplicationRecord
    has_one_attached :image
end

app/models/rig.rb
class Rig < ApplicationRecord
    has_one_attached :image
end

app/models/ssd.rb
class Ssd < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  before_save :downcase_nickname
  has_one :cart

  validates :email, presence: true, uniqueness: true

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
		@games = Game.all
	end

  def show
    @game = Game.find(params[:id])
  end
	
	def new
		@game = Game.new
	end
	
	def create
		@game = Game.new(game_params)
		if @game.save
			redirect_to games_path, notice: 'Игра успешно добавлена'
		else
			render :new
		end
	end
	
	def edit
		@game = Game.find(params[:id])
	end
	
	def update
		@game = Game.find(params[:id])
		if @game.update(game_params)
			redirect_to games_path, notice: 'Игра успешно обновлена'
		else
			render :edit
		end
	end
	
	def destroy
		@game = Game.find(params[:id])
		@game.destroy
		redirect_to games_path, notice: 'Игра успешно удалена'
	end
	
	private
	
	def game_params
		params.require(:game).permit(:title, :description, :release_date, :req_cpu_core_count, :req_cpu_thread_count, :req_cpu_clock, :req_cpu_cache, :req_gpu_memory, :req_gpu_core_clock, :req_gpu_bus_width, :req_hdd_capacity, :req_ram_memory, :req_ssd_capacity, :image, :min_budget)
	end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gpus_helper.rb
module GpusHelper
end

app/helpers/hdds_helper.rb
module HddsHelper
end

app/helpers/rams_helper.rb
module RamsHelper
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/helpers/ssds_helper.rb
module SsdsHelper
end

app/views/games/edit.html.erb
<h2>Edit Game</h2>
<%= form_with(model: @game, url: game_path(@game), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %><br>
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %><br>
    <%= form.label :release_date %>
    <%= form.date_field :release_date, class: 'form-control' %><br>
    <%= form.label :req_cpu_core_count %>
    <%= form.number_field :req_cpu_core_count, class: 'form-control' %><br>
    <%= form.label :req_cpu_thread_count %>
    <%= form.number_field :req_cpu_thread_count, class: 'form-control' %><br>
    <%= form.label :req_cpu_clock %>
    <%= form.number_field :req_cpu_clock, step: 0.01, class: 'form-control' %><br>
    <%= form.label :req_cpu_cache %>
    <%= form.number_field :req_cpu_cache, class: 'form-control' %><br>
    <%= form.label :req_gpu_memory %>
    <%= form.number_field :req_gpu_memory, class: 'form-control' %><br>
    <%= form.label :req_gpu_core_clock %>
    <%= form.number_field :req_gpu_core_clock, step: 0.01, class: 'form-control' %><br>
    <%= form.label :req_gpu_bus_width %>
    <%= form.number_field :req_gpu_bus_width, class: 'form-control' %><br>
    <%= form.label :req_hdd_capacity %>
    <%= form.number_field :req_hdd_capacity, class: 'form-control' %><br>
    <%= form.label :req_ram_memory %>
    <%= form.number_field :req_ram_memory, class: 'form-control' %><br>
    <%= form.label :req_ssd_capacity %>
    <%= form.number_field :req_ssd_capacity, class: 'form-control' %><br>
    <%= form.label :min_budget %>
    <%= form.number_field :min_budget, class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
      <% if @game.image.attached? %>
      <div>
        <%= image_tag(@game.image, width: 300) %>
      </div>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.submit 'Update Game' %>
  </div>
<% end %>

app/views/games/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main>
    <div class="game__show-style">
      <h2 class="components__title-all">Games</h2>
        <div class="container">
          <div class="component__logo all__components">
            <% @games.each do |game| %>
              <div class="component__item">
                <div class="component__title-main"><%= link_to game.title, "/games/#{game.id}" %></div>
                <%= image_tag(game.image) %>
                <div class="component__description"><br>
                  <p>Released: <%= game.release_date %></p>
                  <span class="more__info"><%= link_to 'See more', "/games/#{game.id}" %></span>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>

app/views/games/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.cdnfonts.com/css/boge" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "main", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <header class="header">
        <nav class="nav">
          <div class="logo">
            <%= link_to 'PCFG', root_path, class:'logo' %>
          </div>
          <ul class="menu">
            <li class="menu__list">
              <%= link_to 'Home', root_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
               <%= link_to 'Catalogue', catalogue_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'Configurator', configurator_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'News', news_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'About Us', about_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'FAQ / Support', support_path, class:'menu__link' %>
            </li>
          </ul>
          <div class="basket">
            <a class="basket" href="#">
              <%= image_tag ("logos/cart.png"), height:"40px", alt:"cart" %>
              <!-- <span>1</span> -->
            </a>
          </div>
          <div class="menu__login">
            <ul class="menu__login">
              <li class="menu__list">
                <a class="menu__link" href="#">Sing up</a>
              </li>
              <li class="menu__list">
                <a class="menu__link" href="#">Login</a>
              </li>
            </ul>
          </div>
        </nav>
    </header>
<!-- header section ends -->
<!-- main section starts -->
   <main>
    <h1>Create new Game</h1>
    <%= form_with(model: @game, local: true) do |form| %>
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %><br>
        <%= form.label :description %>
        <%= form.text_field :description, class: 'form-control' %><br>
        <%= form.label :release_date %>
        <%= form.date_field :release_date, class: 'form-control' %><br>
        <%= form.label :req_cpu_core_count %>
        <%= form.number_field :req_cpu_core_count, class: 'form-control' %><br>
        <%= form.label :req_cpu_thread_count %>
        <%= form.number_field :req_cpu_thread_count, class: 'form-control' %><br>
        <%= form.label :req_cpu_clock %>
        <%= form.number_field :req_cpu_clock, step: 0.01, class: 'form-control' %><br>
        <%= form.label :req_cpu_cache %>
        <%= form.number_field :req_cpu_cache, class: 'form-control' %><br>
        <%= form.label :req_gpu_memory %>
        <%= form.number_field :req_gpu_memory, class: 'form-control' %><br>
        <%= form.label :req_gpu_core_clock %>
        <%= form.number_field :req_gpu_core_clock, step: 0.01, class: 'form-control' %><br>
        <%= form.label :req_gpu_bus_width %>
        <%= form.number_field :req_gpu_bus_width, class: 'form-control' %><br>
        <%= form.label :req_hdd_capacity %>
        <%= form.number_field :req_hdd_capacity, class: 'form-control' %><br>
        <%= form.label :req_ram_memory %>
        <%= form.number_field :req_ram_memory, class: 'form-control' %><br>
        <%= form.label :req_ssd_capacity %>
        <%= form.number_field :req_ssd_capacity, class: 'form-control' %><br>
        <%= form.label :min_budget %>
        <%= form.number_field :min_budget, class: 'form-control' %><br>
        <div class="field">
          <%= form.label :image %>
          <%= form.file_field :image %>
        </div>
      </div>
      <div class="actions">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
    <%= link_to 'Back', games_path %>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <footer class="footer">
      <nav class="nav">
          <div class="logo">
            <%= link_to 'PCFG', root_path, class:'logo' %>
          </div>
          <ul class="menu">
            <li class="menu__list">
              <%= link_to 'Home', root_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
               <%= link_to 'Catalogue', catalogue_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'Configurator', configurator_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'News', news_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'About Us', about_path, class:'menu__link' %>
            </li>
            <li class="menu__list">
              <%= link_to 'FAQ / Support', support_path, class:'menu__link' %>
            </li>
          </ul>
          <ul class="social">
            <li class="social__item">
              <%= link_to(image_tag("logos/yt.png", height: "40px", alt: "cart"), "https://www.youtube.com/") %>
            </li>
            <li class="social__item">
              <%= link_to(image_tag("logos/tg.png", height: "40px", alt: "cart"), "https://telegram.org/") %>
            </li>
            <li class="social__item">
              <%= link_to(image_tag("logos/inst.png", height: "40px", alt: "cart"), "https://www.instagram.com/") %>
            </li>
          </ul>
        </nav>
    </footer>
<!-- footer section ends -->
    </div>
  </body>
</html>

app/views/games/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
  <main>
    <div class="game__show-style">
      <div class="container">
        <h1><%= @game.title %></h1>
        <% if @game.image.attached? %>
          <div>
            <%= image_tag(@game.image) %>
          </div>
        <% end %>
        <div class="main__component-info">
          <p><%= @game.description %></p>
        </div>
        <div class="action-buttons__all">
          <%= link_to "Edit game", edit_game_path(@game) %>
          <%= button_to 'Delete game', game_path(@game), method: :delete %><br>
          <%= link_to "All games", games_path %>
        </div>
      </div>
    </div>
  </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>