config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  
  get '/main', to: 'main#index'
  get '/catalogue', to: 'main#catalogue'
  get '/configurator', to: 'configurator#index'

  resources :components
  resources :catalogue
  resources :configurator
  resources :games


  resource :session, only: %i[new create destroy]
  resources :users
  resources :line_items, only: [:create, :update, :destroy]

  resources :rams
  resources :ssds
  resources :hdds
  resources :motherboards
  resources :cpus
  resources :gpus
  resources :power_supplies
  resources :rigs
  resources :coolers
  

  get 'session', to: 'sessions#new'
  get 'step1', to: 'configurator#step1'
  post 'step1_submit', to: 'configurator#step1_submit'
  get 'step2', to: 'configurator#step2'
  post 'step2_submit', to: 'configurator#step2_submit'
  get 'step3', to: 'configurator#step3'
  post 'step3_submit', to: 'configurator#step3_submit'
  get 'results', to: 'configurator#results'
  post 'results', to: 'configurator#results'
  patch '/users/:id', to: 'users#update', as: :update_user

  get '/step2', to: 'configurator#step2'
  get '/step3', to: 'configurator#step3'
  get '/main', to: 'components#show'
  get '/cart', to: 'cart#index'
  get '/news', to: 'main#news'
  get '/support', to: 'main#support'
  get '/about', to: 'main#about'
  get '/login', to: 'main#login'
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :line_items, dependent: :destroy

    def add_component(component)
        line_item = line_items.find_by(component_id: component.id)
        if line_item
          line_item.quantity += 1
        else
          line_item = line_items.build(component_id: component.id)
        end
        line_item.save
    end
end

app/models/component.rb
class Component < ApplicationRecord
    has_one_attached :image
    has_many :line_items
end

app/models/cooler.rb
class Cooler < ApplicationRecord
    has_one_attached :image
end

app/models/cpu.rb
class Cpu < ApplicationRecord
    has_one_attached :image
end

app/models/game.rb
class Game < ApplicationRecord
    has_one_attached :image
end

app/models/gpu.rb
class Gpu < ApplicationRecord
    has_one_attached :image
end

app/models/hdd.rb
class Hdd < ApplicationRecord
    has_one_attached :image
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :component
  belongs_to :cart
end

app/models/motherboard.rb
class Motherboard < ApplicationRecord
    has_one_attached :image
end

app/models/power_supply.rb
class PowerSupply < ApplicationRecord
    has_one_attached :image
end

app/models/ram.rb
class Ram < ApplicationRecord
    has_one_attached :image
end

app/models/rig.rb
class Rig < ApplicationRecord
    has_one_attached :image
end

app/models/ssd.rb
class Ssd < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  before_save :downcase_nickname
  has_one :cart

  validates :email, presence: true, uniqueness: true

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/rigs_controller.rb
class RigsController < ApplicationController
  def index
    @rigs = Rig.all
  end

  def show
    @rig = Rig.find(params[:id])
  end

  def new
    @rig = Rig.new
  end

  def create
    @rig = Rig.new(rig_params)
    if @rig.save
      redirect_to @rig
    else
      render 'new'
    end
  end

  def edit
    @rig = Rig.find(params[:id])
  end

  def update
    @rig = Rig.find(params[:id])
    if @rig.update(rig_params)
      redirect_to @rig
    else
      render 'edit'
    end
  end

  def destroy
    @rig = Rig.find(params[:id])
    @rig.destroy
    redirect_to rams_path
  end

  private

  def rig_params
    params.require(:rig).permit(:brand, :model, :form_factor, :drive_bays, :price, :image, :rating)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gpus_helper.rb
module GpusHelper
end

app/helpers/hdds_helper.rb
module HddsHelper
end

app/helpers/rams_helper.rb
module RamsHelper
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/helpers/ssds_helper.rb
module SsdsHelper
end

app/views/rigs/edit.html.erb
<h2>Edit rigs</h2>
<%= form_with(model: @rig, url: rig_path(@rig), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %><br>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: 'form-control' %><br>
    <%= form.label :form_factor %>
    <%= form.text_field :form_factor, class: 'form-control' %><br>
    <%= form.label :drive_bays %>
    <%= form.number_field :drive_bays, class: 'form-control' %><br>
    <%= form.label :price %>
    <%= form.number_field :price, step: "0.01", class: 'form-control' %><br>
    <%= form.label :rating %>
    <%= form.number_field :rating, step: "0.01", class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
      <% if @rig.image.attached? %>
      <div>
        <%= image_tag(@rig.image) %>
      </div>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.submit 'Update rigs' %>
  </div>
<% end %>

app/views/rigs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main style="background: linear-gradient(to bottom, #000000, #1a0d0d, #1a0d0d, #000000)">
    <div class="container">
      <h2 class="components__title-all">Rig</h2>
      <div class="component__logo all__components">
        <% @rigs.each do |rig| %>
          <div class="component__item">
            <div class="component__title-main"><%= link_to rig.brand, "/rigs/#{rig.id}" %></div>
            <%= image_tag(rig.image) %>
            <div class="component__description"><br>
              <%= rig.model %>
              <span class="description__label"></span>
              <% rating = rig.rating.round(1) %>
              <span class="stars">
                <% for i in 1..5 do %>
                  <% if rating >= i %>
                    <%= image_tag('bg/star.png') %>
                  <% elsif rating >= i - 0.5 && rating < i %>
                    <%= image_tag('bg/half-star.png') %>
                  <% else %>
                    <%= image_tag('bg/empty-star.png') %>
                  <% end %>
                <% end %>
              </span>
              <span class="price__label">Price: <%= rig.price %> $USD</span>
              <span class="more__info"><%= link_to 'See more', "/rigs/#{rig.id}" %></span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>

app/views/rigs/new.html.erb
<h1>Create new Rig</h1>

<%= form_with(model: @rig, local: true) do |form| %>
  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, class: 'form-control' %><br>
    <%= form.label :brand %>
    <%= form.text_field :brand, class: 'form-control' %><br>
    <%= form.label :form_factor %>
    <%= form.text_field :form_factor, class: 'form-control' %><br>
    <%= form.label :drive_bays %>
    <%= form.number_field :drive_bays, class: 'form-control' %><br>
    <%= form.label :price %>
    <%= form.number_field :price, step: "0.01", class: 'form-control' %><br>
    <%= form.label :rating %>
    <%= form.number_field :rating, step: "0.01", class: 'form-control' %><br>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', rigs_path %>

app/views/rigs/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PCFG Support</title>
    <%= render 'layouts/head' %>
    <%= stylesheet_link_tag('/support/styles') %>
  </head>
  <body>
<!-- header section starts -->
    <%= render 'layouts/header' %>
<!-- header section ends -->
<!-- main section starts -->
   <main style="background: linear-gradient(to bottom, #000000, #1a0d0d, #1a0d0d, #000000)">
    <div class="container">
      <h1><%= @rig.brand %></h1>
      <% if @rig.image.attached? %>
        <div class="component-pic">
          <%= image_tag(@rig.image) %>
        </div>
      <% end %>
      <div class="main__component-info">
        <p>Model: <%= @rig.model %></p>
        <p>Form factor: <%= @rig.form_factor %></p>
        <p>Price: <%= number_to_currency(@rig.price) %></p>
      </div>
      <div class="action-buttons__all">
        <%= link_to "Edit component", edit_rig_path(@rig) %>
        <%= button_to 'Delete component', rig_path(@rig), method: :delete %><br>
        <%= link_to "All Rigs", rigs_path %>
      </div>
    </div>
   </main>
<!-- main section ends -->
<!-- footer section starts -->
    <%= render 'layouts/footer' %>
<!-- footer section ends -->
    </div>
  </body>
</html>